### ISSUE TITLE
Poll / Quiz / Trivia

### ISSUE THREAD

**Issue by Phoenix2k** [Phoenix2k/discbot#7]
Makes quizzes and keeps track of progress in the form of leaderboards.

## Command

One of these:

```sh
!poll
```

Or
```sh
!quiz
```

Or even
```sh
!trivia
```

## Arguments

List any arguments the command is supposed to take in and what they're supposed to do.

| Argument | Explanation | Example
|:----------|:------------|:--------|
| add topic <topic> | Creates a new topic | `!quiz create music`
| add question \<topic> \<question> \<answer1, answer2> | Adds a question to a specific topic. Answers can be separated with a comma. Each separate "option" should be in double quotes |  `!quiz question add music "Who created the song Culture of Fear?" "Thievery Corporation", "Mr. Lif"` |
| answer \<answer> | Gives an answer to an ongoing question | `!quiz answer Thievery Corporation` |
| edit question \<topic> \<questionId> \<question> \<answer1, answer2> | Edits an existing question the user has created |  `!quiz edit question 23 "Who created the song Culture of Fear?" "Thievery Corporation", "Mr. Lif"` |
| edit topic \<topicId> <topic> | Edits an existing topic |  `!quiz edit topic 1 music |
| leaderboard \<topic> | Prints a table with progress on a specific topic | `!quiz leaderboard music` |
| leaderboards | Prints a table with progress on all topics | `!quiz leaderboards` |
| list questions \<topic> | Lists all questions the user has created for a specific topic | `!quiz list questions music` |
| list topics | Lists all available topics | `!quiz list topics` |
| remove question \<topic> \<questionId> | Removes a question from a specific topic | `!quiz remove question music 23`
| remove topic \<topic> | Removes an empty topic | `!quiz remove music`
| start \<topic> | Starts a quiz on a chosen topic | `!quiz start music` |

## Output

Topic created:

> @username **\<topic>** created ✅

Topic already exists:

> @username **\<topic>** already exists.

Start message:

> @everyone Starting quiz in 1 minute …

Start message if already started:

> @username I've already started another quiz. Wait until it's over.

Correct answer:

> @username **\<answer>** is correct! 🎉

Incorrect answer:

> @username **\<answer>** was not correct.

Question added:

> @username **\<question>** added. You now rank #X on the leaderboard for new content creators.

## Roadbocks

Waiting on #8

## Todo

- [ ] Add quiz commands
- [ ] Create schemas for topics, answers and leaderboards
- [ ] Create parsers for dealing with quiz commands

## Things to track

- Who answered a question and when
- Was the answer correct or not
- Who submitted questions and how many

## Other things to consider

- Admin UI for managing and editing questions/topics?
